// Usage:
// - Import canonical gateway error-code constants to avoid scattered string literals.
// - Keep frontend labels/parsing aligned with Rust gateway error definitions.

export const GatewayErrorCodes = {
  ALL_PROVIDERS_UNAVAILABLE: "GW_ALL_PROVIDERS_UNAVAILABLE",
  UPSTREAM_ALL_FAILED: "GW_UPSTREAM_ALL_FAILED",
  NO_ENABLED_PROVIDER: "GW_NO_ENABLED_PROVIDER",
  UPSTREAM_TIMEOUT: "GW_UPSTREAM_TIMEOUT",
  UPSTREAM_CONNECT_FAILED: "GW_UPSTREAM_CONNECT_FAILED",
  UPSTREAM_5XX: "GW_UPSTREAM_5XX",
  UPSTREAM_4XX: "GW_UPSTREAM_4XX",
  UPSTREAM_READ_ERROR: "GW_UPSTREAM_READ_ERROR",
  UPSTREAM_BODY_READ_ERROR: "GW_UPSTREAM_BODY_READ_ERROR",
  STREAM_ERROR: "GW_STREAM_ERROR",
  STREAM_ABORTED: "GW_STREAM_ABORTED",
  STREAM_IDLE_TIMEOUT: "GW_STREAM_IDLE_TIMEOUT",
  REQUEST_ABORTED: "GW_REQUEST_ABORTED",
  INTERNAL_ERROR: "GW_INTERNAL_ERROR",
  BODY_TOO_LARGE: "GW_BODY_TOO_LARGE",
  INVALID_CLI_KEY: "GW_INVALID_CLI_KEY",
  INVALID_BASE_URL: "GW_INVALID_BASE_URL",
  PORT_IN_USE: "GW_PORT_IN_USE",
  RESPONSE_BUILD_ERROR: "GW_RESPONSE_BUILD_ERROR",
  PROVIDER_RATE_LIMITED: "GW_PROVIDER_RATE_LIMITED",
  PROVIDER_CIRCUIT_OPEN: "GW_PROVIDER_CIRCUIT_OPEN",
  CLI_PROXY_DISABLED: "GW_CLI_PROXY_DISABLED",
  CLI_PROXY_GUARD_ERROR: "GW_CLI_PROXY_GUARD_ERROR",
  HTTP_CLIENT_INIT: "GW_HTTP_CLIENT_INIT",
  ATTEMPT_LOG_CHANNEL_CLOSED: "GW_ATTEMPT_LOG_CHANNEL_CLOSED",
  ATTEMPT_LOG_ENQUEUE_TIMEOUT: "GW_ATTEMPT_LOG_ENQUEUE_TIMEOUT",
  ATTEMPT_LOG_DROPPED: "GW_ATTEMPT_LOG_DROPPED",
  REQUEST_LOG_CHANNEL_CLOSED: "GW_REQUEST_LOG_CHANNEL_CLOSED",
  REQUEST_LOG_ENQUEUE_TIMEOUT: "GW_REQUEST_LOG_ENQUEUE_TIMEOUT",
  REQUEST_LOG_WRITE_THROUGH_ON_BACKPRESSURE: "GW_REQUEST_LOG_WRITE_THROUGH_ON_BACKPRESSURE",
  REQUEST_LOG_WRITE_THROUGH_RATE_LIMITED: "GW_REQUEST_LOG_WRITE_THROUGH_RATE_LIMITED",
  REQUEST_LOG_DROPPED: "GW_REQUEST_LOG_DROPPED",
} as const;

export type GatewayErrorCode = (typeof GatewayErrorCodes)[keyof typeof GatewayErrorCodes];
