name: 功能请求
description: 提出一个新功能或改进建议
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！请尽可能详细地描述您的需求。

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 请选择功能类型
      options:
        - 新增功能
        - 现有功能改进
        - UI/UX 优化
        - 性能优化
        - 其他
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 相关平台
      description: 此功能与哪个平台相关？
      options:
        - 全平台通用
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: 当前 AIO Coding Hub 版本
      description: "可在应用设置页面查看，例如: v1.2.3"
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题背景
      description: 这个功能请求是否与某个问题相关？请描述
      placeholder: "当我尝试做...时，我感到很困扰，因为..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 清晰简洁地描述您希望实现什么
      placeholder: "我希望能够..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 描述您考虑过的任何替代解决方案或功能
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 设计参考/截图
      description: 如果有 UI 相关的建议，可以添加设计参考或截图（可拖拽上传）
      placeholder: "拖拽图片到这里..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 添加任何其他关于功能请求的上下文信息
    validations:
      required: false
